---
- name: install packages homebrew
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
  - httpie
  - jq
  - ripgrep
  - wget
  - ipmitool
  - terraform
  - git
  - git-filter-repo
  - ipcalc

  # osx defaults reference:
  # https://github.com/mathiasbynens/dotfiles/blob/master/.macos
  # https://github.com/pawelgrzybek/dotfiles/blob/master/setup-macos.sh


- osx_defaults:
    domain: com.apple.dock
    key: IncludeInternalDebugMenu
    type: int
    value: 24
    state: present
  notify:
  - restart macos dock

- osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present
